version: '2'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  news:
    links:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_REV
        - COMMIT_DATE
    environment:
      - REDIS_URL=redis://cache
    ports:
      - 8080
      - 5432:5432
